// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9iGk3bTsF0ybfgNovi3klJCLP2Di86xQ',
    appId: '1:396153679447:web:a94193909e3358bd90bd12',
    messagingSenderId: '396153679447',
    projectId: 'ctse-project-7cf63',
    authDomain: 'ctse-project-7cf63.firebaseapp.com',
    storageBucket: 'ctse-project-7cf63.appspot.com',
    measurementId: 'G-4645DTYFMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5NVX_A4UDKtx8ZJGfmVo3WG6egSn6Qdk',
    appId: '1:396153679447:android:c13a3abfa0d66cc590bd12',
    messagingSenderId: '396153679447',
    projectId: 'ctse-project-7cf63',
    storageBucket: 'ctse-project-7cf63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8RMqpxwNkFe9TuXi6GijsHu73jklHr7Y',
    appId: '1:396153679447:ios:47a6b3ac5d3ca62790bd12',
    messagingSenderId: '396153679447',
    projectId: 'ctse-project-7cf63',
    storageBucket: 'ctse-project-7cf63.appspot.com',
    iosClientId: '396153679447-79vjlreus4i8g49on0do4hdkkm4kgj7m.apps.googleusercontent.com',
    iosBundleId: 'com.example.ctseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8RMqpxwNkFe9TuXi6GijsHu73jklHr7Y',
    appId: '1:396153679447:ios:47a6b3ac5d3ca62790bd12',
    messagingSenderId: '396153679447',
    projectId: 'ctse-project-7cf63',
    storageBucket: 'ctse-project-7cf63.appspot.com',
    iosClientId: '396153679447-79vjlreus4i8g49on0do4hdkkm4kgj7m.apps.googleusercontent.com',
    iosBundleId: 'com.example.ctseProject',
  );
}
